accounts/main/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

accounts/urls.py
from django.urls import path, include
from .views import register
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm

app_name = 'accounts'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', authentication_form=AuthenticationForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todolist.urls', namespace='todolist')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

todolist/urls.py
from django.urls import path, include
from .views import (
    todos_list,
    todos_retrieve,
    todos_create,
    todos_update,
    todos_delete,
    todos_search,
)

app_name = 'todolist'

urlpatterns = [
    path('', todos_list, name='index'),
    path('create/', todos_create, name='todosCreate'),
    path('search/', todos_search, name='todosSearch'),
    path('<int:pid>/', todos_retrieve, name='todosGet'),
    path('<int:pid>/update/', todos_update, name='todosUpdate'),
    path('<int:pid>/delete/', todos_delete, name='todosDelete'),
]

accounts/models.py
from django.db import models

# Create your models here.

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class ToDo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    due_date = models.DateField()
    
    class Meta:
        verbose_name = 'todo'
        verbose_name_plural = 'todos'

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class HiddenUserCreationForm(UserCreationForm):
    # Overriding first_name field
    first_name = forms.CharField(max_length=50, required=True, label='First Name')
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Defining our own label for password2 field
        self.fields['password2'].label = 'Confirm Password'

todolist/forms.py
from django import forms
from .models import ToDo
class ToDoCreateForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['name', 'due_date']
        widgets = {'due_date' : forms.DateInput(attrs={'type':'date'})}
        # widgets = {'due_date' : forms.SelectDateWidget}
        

class ToDoSearchForm(forms.ModelForm):
    class Meta:
        model = ToDo
        fields = ['name']

accounts/views.py
from django.shortcuts import render, redirect
from .forms import HiddenUserCreationForm
from django.contrib.auth import login, authenticate

def register(request):
    if request.method == 'POST':
        form = HiddenUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('todolist:index')
    else:
        form = HiddenUserCreationForm()
    
    context = {'form':form}
    return render(request, 'accounts/register.html', context)

todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import ToDo
from .forms import ToDoCreateForm, ToDoSearchForm
from django.contrib.auth.decorators import login_required

# CRUD--> Create, Retrieve, Update, Delete

# Create
@login_required
def todos_create(request):
    # to take input from user we need FORMS
    if request.method == 'POST':
        form = ToDoCreateForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()

            return redirect("todolist:index")
    else:
        form = ToDoCreateForm()
        context = {"form": form}
        return render(request, "todolist/todos_create.html", context)

# ListALL
@login_required
def todos_list(request):
    user = request.user
    # list_of_todos is a QUERYSET
    # list_of_todos = user.todo_set.all()
    qs = ToDo.objects.filter(user=user)
    
    context = {"todos": qs}
    return render(request, "todolist/todos_list.html", context)

# Retrieve
@login_required
def todos_retrieve(request, pid):
    user = request.user
    qs = ToDo.objects.filter(user=user)
    todo_objs = qs.filter(id=pid)
    context = {"todos": todo_objs}
    return render(request, "todolist/todos_retrieve.html", context)

# Update
@login_required
def todos_update(request, pid):
    user = request.user
    qs = ToDo.objects.filter(user=user)
    todo_obj = qs.get(id=pid)
    if request.method == 'POST':
        form = ToDoCreateForm(request.POST, instance=todo_obj)
        if form.is_valid():
            form.save()
            return redirect("todolist:index")
    else:
        form = ToDoCreateForm(instance=todo_obj)
        context = {"form": form}
    return render(request, "todolist/todos_update.html", context)

# Delete
@login_required
def todos_delete(request, pid):
    user = request.user
    qs = ToDo.objects.filter(user=user)
    todo_obj = qs.get(id=pid)
    todo_obj.delete()
    return redirect("todolist:index")

# Search
@login_required
def todos_search(request):
    if request.method == 'POST':
        form = ToDoSearchForm(request.POST)
        if form.is_valid():
            user = request.user
            todo_name = form.cleaned_data.get("name")

            qs = ToDo.objects.filter(user=user)

            todo_objs = qs.filter(name__icontains=todo_name)

            context = {"todos": todo_objs, "searchedItem": todo_name}
            return render(request, "todolist/todos_retrieve.html", context)
    else:
        form = ToDoSearchForm()
        context = {"form": form}
    return render(request, "todolist/todos_search.html", context)

accounts/templates/accounts/index.html
{% include 'base.html' %}
{% block content %}
    <h2>Index Page</h2>
    {% if user.is_authenticated %}
        <p>{{ user.username }} is logged in</p>
    {% else %}
        <p>You are NOT logged in</p>
    {% endif %}
{% endblock content %}

accounts/templates/accounts/login.html
{% include 'base.html' %}
{% block content %}
<h2>Login Page</h2>
<form method="POST">
    {% csrf_token %}
    {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
        </p>
    {% endfor %}
    <div style="color: red">{{ form.non_field_errors }}</div>
    <button type="submit">Login</button>
</form>

{% endblock content %}

accounts/templates/accounts/register.html
{% include 'base.html' %}
{% block content %}
<h2>Registration Page</h2>
<form method="POST">
    {% csrf_token %}
    {% for field in form %}
        <p>
            {{ field.label_tag }}<br>
            {{ field }}
            {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
            {% endfor %}
        </p>
    {% endfor %}
    <button type="submit">Sign up</button>
</form>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDoList</title>
</head>

<body>
    <a href="{% url 'todolist:index' %}">Home</a>
    {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'accounts:register' %}">Register</a>
        <a href="{% url 'accounts:login' %}">Login</a>
    {% endif %}
    
    {% block content %}
    {% endblock content %}
</body>

</html>

todolist/templates/todolist/todos_create.html
{% extends 'base.html' %}
{% block content %}
<h3>Create a TODO</h3>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type = "submit">ADD</button>
</form>

{% endblock content %}

todolist/templates/todolist/todos_list.html
{% extends 'base.html' %}
{% block content %}
<h3>HOMEPAGE -- List of TODOS</h3>
<hr>
<a href="{% url 'todolist:todosCreate' %}">Add a TASK</a>
<br>
<a href="{% url 'todolist:todosSearch' %}">Search</a>
<hr>
<ul>
    {% for todo in todos %}
    <li><a href="{% url 'todolist:todosGet' todo.id %}">{{todo.name}}</a> -- Due on {{todo.due_date}}</li>
    {% endfor %}
</ul>

{% endblock content %}

todolist/templates/todolist/todos_retrieve.html
{% extends 'base.html' %}
{% block content %}
<h3>Search results for "{{ searchedItem }}"</h3>

<ul>
    {% for todo in todos %}
    <li><a href="{% url 'todolist:todosGet' todo.id %}">{{todo.name}}</a> -- Due on {{todo.due_date}}
        <a href="{% url 'todolist:todosUpdate' todo.id %}">Update</a>
        <a href="{% url 'todolist:todosDelete' todo.id %}">Delete</a>
    </li>
    {% endfor %}
</ul>

{% endblock content %}

todolist/templates/todolist/todos_search.html
{% extends 'base.html' %}
{% block content %}
<h3>Search for TASK</h3>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Search</button>
</form>
{% endblock content %}

todolist/templates/todolist/todos_update.html
{% extends 'base.html' %}
{% block content %}
<h3>Update this TODO task</h3>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Update</button>
</form>

{% endblock content %}